### ISSUE TITLE
Mise à jour vers le RGAA 3 2017 ?

### ISSUE THREAD

**Issue by PhilippeVay** [DISIC/assistant-rgaa#12]
Bonjour,

la dernière version du RGAA 3 présente quelques modifications par rapport à la version utilisée par cette extension (RGAA 3 2016) avec 3 tests créés, 3 tests supprimés et une douzaine de tests modifiés. Est-il prévu une mise à jour de cette extension ?  
Question bonus : est-il prévu d'autres nouveautés concernant cette extension ?

**Comment by sbonaventure** [comment]
Bonjour @PhilippeVay 

L'extension à été forkée et publiée ici https://github.com/empreinte-digitale/assistant-rgaa avec le référentiel dans sa version 2017. Cette extension à également été publie sur les catalogues d'applications Chrome & Firefox pour une installation plus facile.

Vous trouverez plus d'informations à ce sujet [sur le blog d'Empreinte Digitale](https://blog.empreintedigitale.fr/2019/05/02/publication-de-lassistant-rgaa-avec-le-referentiel-3-2017/)
