### ISSUE TITLE
broken external link in doc/architecture.md (redux-saga)

### ISSUE THREAD

**Issue by dzc34** [DISIC/assistant-rgaa#2]
http://yelouafi.github.io/redux-saga/  ---> Error 404

Use one of the following links:
- https://github.com/redux-saga/redux-saga
- https://redux-saga.js.org/

**Comment by Etat-Plateforme** [comment]
Thank you, this is now fixed by https://github.com/DISIC/assistant-rgaa/commit/84178e0f5248a8d260d6a396a16a028f107d4729 in the master branch.
