### ISSUE TITLE
Unrecognized manifest key 'applications'

### ISSUE THREAD

**Issue by Lucas-C** [DISIC/assistant-rgaa#5]
Bonjour.

J'obtiens cette erreur en essayant d'installer la dernière version 1.0.2 dans Chrome 61.0.3163.100, en mode développeur (rien ne se passe quand j'essaie sans ce mode) :

<img alt="Screenshot erreur Unrecognized manifest key 'applications'" src="https://user-images.githubusercontent.com/925560/32090389-754a65d8-baef-11e7-852e-9416613d3456.png">

**Comment by Leimi** [comment]
Bonjour Lucas, merci pour ton retour.

Bizarre que l'installation sans être en mode développeur ne fonctionne pas. As-tu essayé de dézipper le dossier avant puis de glisser-déposer le tout sur la page d'extensions ?

À part ça, l'avertissement n'impacte pas le bon fonctionnement de l'extension. Il avertit que la clé `applications` du fichier [manifest.json](https://github.com/DISIC/assistant-rgaa/blob/master/manifest.json) n'est pas comprise par Chrome ; cette clé n'est utilisée aujourd'hui que par Firefox.

**Comment by Lucas-C** [comment]
En effet, j'ai réalisé ensuite que ça fonctionnait en passant par "Charger l'extension non empaquetée".

Par contre au simple drag&drop, j'ai une popup d'erreur puis le message suivant dans le menu Extensions:

<img alt="assistant-rgaa-1 0 2-cannot-unzip-popup" src="https://user-images.githubusercontent.com/925560/32097205-00afc0fa-bb09-11e7-9620-e05376f38444.png">

<img alt="assistant-rgaa-1 0 2-cannot-unzip-in-extensions-menu" src="https://user-images.githubusercontent.com/925560/32097220-1149b3d0-bb09-11e7-87e0-c0f7efa7b7ad.png">

Je te laisse fermer ce ticket si tu veux, j'ai résolu mon problème
